Fixed problems with Makefile
1. don't include any files that are the byproduct of the compilation
process in your source repository.  For instance, *.o files should not
be in the git repository as they will disrupt the build process when
cloning to a new machine (specifically, millionare.o was compiled on
i386 architecture, which is incompatible with binaries compiled on the
x86_64 architecture that I am using)
2. the "millionaire" target was attempting to compile a program named
millionaire using only millionaire.cpp as the source file, but
millionaire.cpp does not contain a main() {} routine, the result was
 an error about "undefined reference to main"
3. the recipe for main did not include main.o as a source file
 (though it is included on the dependency line) so there were many
 "undefined reference to... " errors.